Start turn redux (et al.)
FRA-JYLL/jyll pull request #49
Opened 2020-12-11 16:35 UTC by Yan-rlathotep

La PR de l'enfer

2020-12-21 13:27 UTC, JeremyLauret requested changes
La logique me semble bien, pas de soucis de nommage ou de dev, j'ai juste un doute sur le typage des class id :p

2020-12-21 13:27 UTC, JeremyLauret commented on frontend/src/pages/GamePage/GamePage.component.tsx
> +              {fullPlayer?.isReady ? t('game.ui.waiting') : t('game.ui.endTurn')}
`?.` operator, so fancy

2020-12-21 13:27 UTC, JeremyLauret commented on frontend/src/redux/game/types.ts
> +  classIndex: string;
Sauf erreur de ma part c'est un integer ? C'est sensé représenter le type de bâtime que c'est (ie un sorte d'id)

2020-12-21 13:27 UTC, JeremyLauret commented on frontend/src/redux/game/types.ts
> +  class_index: string;
Idem

2020-12-21 13:27 UTC, JeremyLauret commented on frontend/src/redux/game/types.ts
> +  buildingCopyId: string;
Idem, ce ne sont que des int

2020-12-21 13:27 UTC, JeremyLauret commented on frontend/src/redux/game/types.ts
> +  domainIndex: string;
Idem

2020-12-21 13:27 UTC, JeremyLauret commented on frontend/src/redux/game/types.ts
> +  building_copy_id: string;
Idem

2020-12-21 13:27 UTC, JeremyLauret commented on frontend/src/redux/game/types.ts
> +  domain_index: string;
Idem

2020-12-21 13:27 UTC, JeremyLauret commented on frontend/src/redux/game/types.ts
> +  nextTechnologyClassIndex: string;
J'arrête d'écrire idem partout, tu m'as compris

2020-12-21 19:16 UTC, JeremyLauret approved these changes

2020-12-22 05:27 UTC, Yan-rlathotep commented on frontend/src/redux/game/types.ts
> +  classIndex: string;
On utilise des strings pour tous les id au cas où on utiliserait des slugs dans le back à la place des integers.

2020-12-23 09:07 UTC, merged