Improve update between turns
FRA-JYLL/jyll pull request #52
Opened 2020-12-24 10:59 UTC by Yan-rlathotep

/!\ The player will now be stuck on "WAITING..." if the backend answers with a 200 while not handling the end turn request properly, e.g. when a CLOSE action is required. Current behaviour of the backend: raise an error, but answer with a 200 anyway.

2020-12-25 21:38 UTC, JeremyLauret requested changes
Rien à redire sur cette PR en soi, si ce n'est que le back est un peu en carton... :p
J'ai mis "request changes" malgré tout par rapport à mon commentaire.

2020-12-25 21:38 UTC, JeremyLauret commented on frontend/src/pages/GamePage/GamePage.component.tsx
> +  }, [getNewTurnData, timer]);
Deux commentaires :
1) Maintenant tu peux utiliser la route `/api/game/<pk>/generation/` pour récupérer la génération uniquement :D
2) Est-ce que ce ne serait pas l'occasion de faire en sorte que ce call ne soit fait à répétition que lorsque le joueur est ready ? C'est un peu le sujet de la branche à mon sens

2020-12-26 08:20 UTC, Yan-rlathotep commented on frontend/src/pages/GamePage/GamePage.component.tsx
> +  }, [getNewTurnData, timer]);
2. Oui, j'ai juste oublié de le faire xD

2020-12-26 11:58 UTC, JeremyLauret approved these changes
Parfait modulo une possible amélioration

2020-12-26 11:58 UTC, JeremyLauret commented on frontend/src/redux/game/sagas.ts
> +      console.log(newGeneration);
:)

2020-12-26 11:58 UTC, JeremyLauret commented on frontend/src/redux/game/sagas.ts
> +        );
Est-ce qu'on a vraiment besoin de GET toute la game ici ? Est-ce qu'autre chose que la génération peut changer d'un tour à l'autre ? Si ce n'est pas le cas, mieux vaut juste put un `GET_GAME_GENERATION_SUCCESS`

2021-01-20 07:18 UTC, merged